### ISSUE TITLE
2.7.0 Sample data

### ISSUE THREAD

**Issue by aishrimc** [OxfordSKA/OSKAR#11]
In the new version (2.7.0) the sample data for 2.6.1 is not working, it is running into error in the telescope directory. The exact error is "ERROR: Run failed with code -28: a configuration file is missing from the telescope model directory tree." 
It is with the zipped data available with the 2.6.1 release.
What file is missing in the telescope folder of the previous version? And since the official site is not working where can I get the new sample data?
Thanks in advance.

**Comment by fdulwich** [comment]
Since version 2.7.0, an extra file called `position.txt` is required in the telescope model to specify the longitude and latitude of the telescope centre. (These values were previously in the settings file, but should really have been part of the telescope model.)

I've now updated the GitHub release page at https://github.com/OxfordSKA/OSKAR/releases/tag/2.7.0 by attaching the documentation and example data files for the current version.

**Comment by aishrimc** [comment]
Thanks a lot Fred

**Comment by fdulwich** [comment]
No problem :-)
