### ISSUE TITLE
Images in angular coordinates

### ISSUE THREAD

**Issue by parphyam** [OxfordSKA/OSKAR#23]
Is it possible to give as the simulator input a fits image with coordinates specified in comoving Mpc instead of angular coordinates? The image has shape (200,200,300) with the 3rd axis as the frequency axis, and the first 2 as cMpc. The input as a text file (sky.osm) requires RA and Dec to be specified, but in the case of this image, they are not specified.

**Comment by fdulwich** [comment]
If you want to use a FITS image as an OSKAR sky model then you will need to specify a world coordinate system for it so that image pixels can be localised in angular space. (Similar to a real system, sky models used by OSKAR exist independently from other observation/telescope parameters. For this reason sky model components require positional information, since without this it would not be possible to evaluate telescope visibility data.) There may be functions in astropy that could help with the conversion to angular coordinates.

Note that if using images to represent extended emission, be aware that OSKAR will treat each pixel as a compact source, so make sure the pixel separation is appropriate if you want these to remain unresolved. I'm not sure what your other requirements are (and I don't wish to discourage you from trying OSKAR!), but it may be worth checking whether a different type of simulator may be more useful or appropriate for your needs here.

**Comment by parphyam** [comment]
Thanks! As you mentioned the pixel separation has been kept to keep the diffuse emission from being resolved. Also the pixels have been converted to WCS using Astropy. However when the a simulation with the fits file as input is being run using `from_fits_file` class I am getting a `RuntimeError: oskar_interferometer_run_block() failed with code -9 (data type mismatch).` error (full error in text file attached). 
[error.txt](https://github.com/OxfordSKA/OSKAR/files/4204468/error.txt)



I am also attaching a screenshot with the header information in the fits file for your convenience. 

![header](https://user-images.githubusercontent.com/55325472/74532162-7fe85080-4f54-11ea-9d2e-851a18bc3d8a.png)

**Comment by fdulwich** [comment]
Thanks for reporting the error - I'll look into this. Are you using single or double precision for the simulation? In your call to `Sky.from_fits_file` make sure the `precision` argument matches that used to run the simulator (the default is double precision in both cases). If that doesn't fix it then feel free send me an email with the part of your script where you set up the simulation and I'll take a look.

**Comment by parphyam** [comment]
Thanks a lot for your reply! I'll look into the precision part and should I run into more errors I'll let you know.

**Comment by parphyam** [comment]
Hello,
I have solved all the above problems, thanks to your helpful tips. Now one little thing is that I am unable to start oskar GUI. If a write a python script (along the limes of the ones obtained from [https://fdulwich.github.io/oskarpy-doc/](url)), the code works just fine. However, when I type `$ oskar` in the bash, it says `bash: oskar: command not found...` (I had a previous version installation in another machine which opens with `$ oskar`).  Do I need to specify any path in the ~/.bashrc?

**Comment by fdulwich** [comment]
It sounds like the GUI wasn't compiled or installed on the machine you're using, which will be the case if Qt 5 was not found by CMake at compilation time.

**Comment by fdulwich** [comment]
I will close this issue now as I believe it has been resolved.
