### ISSUE TITLE
Spectral variation across input image cube

### ISSUE THREAD

**Issue by parphyam** [OxfordSKA/OSKAR#26]
Hi,
I was wondering if there is any way we can input a fits image cube as sky model with spectral index variation while running a simulation with oskarpy. If I am using a sky.osm file, there is a specific spectral index column where I am specifying it with values like say -0.8. But is there any way I can do it for a fits image as input sky model?

**Comment by fdulwich** [comment]
The best way to do this is probably to use astropy to read the spectral index map as a numpy array and then construct the sky model manually in Python by filling in the spectral index column from the pixel values. (There isn't a way to specify a spectral index map in OSKAR, since all pixels from all FITS files are treated as independent "sources" and are combined internally into a single sky model - trying to introduce inter-dependencies between FITS files would become quite messy!)
