### ISSUE TITLE
Normalise beam at phase does not work for oskarpy

### ISSUE THREAD

**Issue by parphyam** [OxfordSKA/OSKAR#28]
Hi,
If I set `'normalise_beam_at_phase_centre : 'True'`  while running a simulation a simulation using a python script, I get the error given in beam_err.txt. Has the option been disabled for the new oskarpy? Also, is there a way I can make all the beams unit (i.e. there should be no  contribution of beams in the simulation?). 
[beam_err.txt](https://github.com/OxfordSKA/OSKAR/files/4842701/beam_err.txt)

**Comment by fdulwich** [comment]
The option has not been removed or disabled. If you look at the error message you attached more closely you will see there is an extra space at the end of the key name, which is why it failed to set the value. Change `'telescope/normalise_beams_at_phase_centre '` to `'telescope/normalise_beams_at_phase_centre'`. (The default value for this is `True` in any case.)

All station beam effects can be disabled by setting `'telescope/station_type'` to `'Isotropic beam'`.
