### ISSUE TITLE
Writing data into a Measurement Set

### ISSUE THREAD

**Issue by egbdfX** [OxfordSKA/OSKAR#43]
Hi,

I have met a problem when I try to write data into a CASA Measurement Set.

I wrote a python code based on the example on https://fdulwich.github.io/oskarpy-doc/measurement_set.html. But I find that the outputted Measurement Set has different UVW and DATA values in some baselines, comparing with the input. To be more precise, please see the attached document.
[Bug report.pdf](https://github.com/OxfordSKA/OSKAR/files/9260292/Bug.report.pdf)

I use .mat files as inputs to input UVW and DATA, and the output is a .ms Measurement Set. 

Could anyone please give me some advice about this issue?

Thank you very much for your time and help.

Regards,

Xiao

**Comment by fdulwich** [comment]
Unfortunately I don't have enough information to investigate this further at the moment, as I would need to understand the format of your .mat files, and how you are calling the function to write the data.

In any case, you can use the python-casacore package (http://casacore.github.io/python-casacore/) to write data to a Measurement Set, since this is the more standard method.

**Comment by egbdfX** [comment]
Thank you for your response, Fred.

I have sent you the .mat files and my code via email. Please see whether you can download them.

Thank you again!
